blog/urls.py
# ---------------- #
# coding=utf-8     #
# Author:cxw       #
# Date:2017.xx.xx  #
# ---------------- #
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.blog_title, name='blog_title'),
    url(r'^(?P<article_id>\d)/$', views.blog_article, name='blog_detail')
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
from blog import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^favicon.ico$', RedirectView.as_view(url='static/images/favicon.ico')),
    url(r'^$', views.blog_title),
    url(r'^blog/', include(("blog.urls", "blog"), namespace="blog")),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.


class BlogArticles(models.Model):
    title = models.CharField(max_length=300, verbose_name='标题')
    author = models.ForeignKey(User, related_name='blog_posts', verbose_name='作者')
    body = models.TextField(verbose_name='文章内容')
    publish = models.DateTimeField(default=timezone.now, verbose_name='时间')

    class Meta:
        ordering = ("-publish",)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import BlogArticles

# Create your views here.


def blog_title(request):
    blogs = BlogArticles.objects.all()
    return render(request, "blog/titles.html", {"blogs": blogs})


def blog_article(request, article_id):
    # article = BlogArticles.objects.get(id=article_id)
    article = get_object_or_404(BlogArticles, id=article_id)
    pub = article.publish
    return render(request, "blog/content.html", {"article": article, "publish": pub})

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="x-ua-compatible" content="IE=Edge">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
{#    <link rel="stylesheet" href="http://necolas.github.io/normalize.css/">#}
{#    <link rel="stylesheet" href="http://libs.baidu.com/bootstrap/3.0.3/css/bootstrap.min.css">#}
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
</head>
<body>
    {% include "header.html" %}
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    {% include "footer.html" %}
{#<script src="http://libs.baidu.com/jquery/2.0.0/jquery.min.js"></script>#}
{#<script src="http://libs.baidu.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>#}
    {% block javascript %}
    {% endblock %}
</body>
</html>

templates/blog/content.html
<!DOCTYPE html>
<html lang="en">
{% extends "base.html" %}

{% block title %}blog article{% endblock %}

{% block content %}
    <div class="row text-center vertical-middle-sm">
        <h1>{{ article.title }}</h1>
    </div>
    <div class="row">
        <div class="col-xs-12 col-md-8">
            <p class="text-center"><span>{{ article.author.username }}</span><span style="margin-left: 20px">{{ publish }}</span></p>
            <div>
                {{ article.body }}
            </div>
        </div>
    <div class="col-xs-6 col-md-4">
        <h2>广告</h2>
        <p>跟老齐学:www.itdiffer.com</p>
        <img width="200px" src="http://www.mrwallpaper.com/Fluffy-Cat.jpg">
    </div>
    </div>
{% endblock %}

templates/blog/titles.html
 <!DOCTYPE html>
<html lang="en">
{% extends "base.html" %}

{% block title %}blog titles{% endblock %}

{% block content %}
    <div class="row text-center vertical-middle-sm">
        <h1>我的博客</h1>
    </div>
    <div class="row">
        <div class="col-xs-12 col-md-8">
            <ul>
                {% for blog in blogs %}
                    <li><a href="{{ blog.id }}">{{ blog.title }}</a></li>
                {% endfor %}
            </ul>
        </div>
    <div class="col-xs-6 col-md-4">
        <h2>广告</h2>
        <p>跟老齐学:www.itdiffer.com</p>
        <img width="200px" src="http://www.mrwallpaper.com/Fluffy-Cat.jpg">
    </div>
    </div>
{% endblock %}

templates/footer.html
<!DOCTYPE html>
<div class="container">
    <hr>
    <p class="text-center">&copy;2017-2018 &nbsp;东方财富信息股份有限公司</p>
</div>

templates/header.html
<!DOCTYPE html>
{% load staticfiles %}
<div class="container">
    <nav class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
            <a class="navbar-brand" href="http://www.itdiffer.com" target="_blank"><img src="{% static '/images/logo.png'%}" width="100px"> </a>
        </div>
        <div>
            <ul class="nav navbar-nav" role="navigation">
                <li><a href="{% url 'blog:blog_title' %}">BLOG</a> </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#">LOGIN</a></li>
            </ul>
        </div>
    </nav>
</div>